import { PrismaClient } from '@prisma/client'
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import bcrypt from 'bcryptjs'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
    throw new Error("DATABASE_URL is not defined in environment variables");
}

const pool = new Pool({
    connectionString,
});

const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const users = [
    { name: "Dody", email: "dodykindarch@gmail.com" },
    { name: "Ali Kho", email: "wenlee.design76@gmail.com" },
    { name: "Ryan", email: "ryanfahrihusaini@gmail.com" },
    { name: "Adji", email: "adjisensei2410@gmail.com" },
    { name: "Reza", email: "rezaokti123@gmail.com" },
    { name: "Kaza Living", email: "kaza.living@gmail.com" },
    { name: "Putri", email: "pu3shaun@gmail.com" },
    { name: "Rendy", email: "kira.studio@outlook.com" },
    { name: "Ahmad Zainu", email: "ajenahmadm@gmail.com" },
    { name: "Yossi", email: "yossi.ardianto15@gmail.com" },
    { name: "Maya", email: "mayasarinimade@gmail.com" },
    { name: "Alifia", email: "alfianrau08@gmail.com" },
    { name: "Studio_odelapan", email: "studio.odelapan@gmail.com" },
    { name: "Elby", email: "elbyputra32@gmail.com" },
    { name: "Ramdhan Omar", email: "gajah.bengkaks@gmail.com" },
    { name: "Dxdesignkpg", email: "dxdesignkpg@gmail.com" },
    { name: "Arya", email: "arya2nd@gmail.com" },
    { name: "Daniel", email: "daniel.ammar23@gmail.com" },
    { name: "Muhammad Ayi Dirgantara", email: "muhammadayidirgantara@gmail.com" },
    { name: "Billy Bun", email: "ainurrrohman@gmail.com" },
    { name: "Alfian Bachtiar", email: "ian6310@gmail.com" },
    { name: "Dandy", email: "dandy.kanawasena@gmail.com" },
    { name: "Rudy", email: "rudyt07@gmail.com" },
    { name: "Matthew", email: "matthew_rickys@yahoo.com" },
    { name: "Komang Wiana", email: "komangjayu@gmail.com" },
    { name: "Rivaldi Liem", email: "rivaldi.ragiel@gmail.com" },
    { name: "Eart Architecture", email: "eart.architecture@gmail.com" },
    { name: "Fikry", email: "fikrykrayy@gmail.com" },
    { name: "Oryza", email: "oryza.ardiansyah14@gmail.com" },
    { name: "Seniman Belajar", email: "senimanbelajar@gmail.com" },
    { name: "Aji", email: "ajisetiawan0186@gmail.com" },
    { name: "Heru", email: "heruwibowogrup96@gmail.com" },
    { name: "Muhammad Alifiansah", email: "m.alifiansah2@gmail.com" },
    { name: "Sle_mooor", email: "sle.mooor@gmail.com" },
    { name: "Biani", email: "bianintuisi@gmail.com" },
    { name: "Amin Rais", email: "aminarsitek@gmail.com" },
    { name: "Jaril Safii", email: "jaril.saf@gmail.com" },
    { name: "Azi", email: "azissinggih15@gmail.com" },
    { name: "Taufik Nurahman", email: "Kipupikk@gmail.com" },
    { name: "Cecar Sadewo", email: "lingkup.alo@gmail.com" },
    { name: "Adithia Putra", email: "jual.dullu@gmail.com" },
    { name: "Stefanuschristiand97", email: "stefanuschristiand97@gmail.com" },
    { name: "Sherly", email: "sherlychandra7296@gmail.com" },
    { name: "Gilang", email: "gilangd50@gmail.com" },
    { name: "Fx_Purnomo", email: "fx.purnomo@gmail.com" },
    { name: "Yulia", email: "Yuliadihidayat23@gmail.com" },
    { name: "Hilmi", email: "hilmikhairulla@gmail.com" },
    { name: "Vincent", email: "vincentvalen27@gmail.com" },
    { name: "Galih", email: "galihja08@gmail.com" },
    { name: "Salma", email: "salmanalfarizi200703@gmail.com" },
    { name: "Rozi", email: "rozi.samma@gmail.com" },
    { name: "I Nyoman", email: "imagin3design@yahoo.com" },
    { name: "Deri Achdan", email: "deriachdan@gmail.com" },
    { name: "Ade Saputra", email: "adesaputra5858@gmail.com" },
    { name: "Dika Putra", email: "serialcollab71@gmail.com" },
    { name: "Rayen Moore", email: "rayenmoore10@gmail.com" },
    { name: "Kurnia Afirmand", email: "kurnia.afirmand25@gmail.com" },
    { name: "Kus Wandiana", email: "kuswandiana@gmail.com" },
    { name: "Muhammad Ghaffar Assiddiqi", email: "muhammadghaffarassiddiqi@gmail.com" },
    { name: "I Gusti Ngurah Bagus", email: "gustibhw62@gmail.com" },
    { name: "Andy Samosir", email: "andy.samosir07@gmail.com" },
    { name: "Rizki", email: "rizkicp@gmail.com" },
    { name: "Rifqi", email: "guerifqii@gmail.com" },
    { name: "Berlian", email: "berliannurastiputri@gmail.com" },
    { name: "Yuliadihidayt23", email: "yuliadihidayt23@gmail.com" },
    { name: "Maulana", email: "maulanaaishak61@gmail.com" },
    { name: "Tia", email: "tiaworkonly2@gmail.com" },
    { name: "Kaleng Pensil", email: "kalengpensil@gmail.com" },
    { name: "Darren Pirono", email: "darrenpirono@yahoo.com" },
    { name: "Ardikah Wira", email: "ardikahwirasaputra@gmail.com" },
    { name: "Raffi Ariana Razaan", email: "razaanrafi69@gmail.com" },
    { name: "Anakin Skywalker", email: "area55studio.works@gmail.com" },
    { name: "Endra Wibisono", email: "endrawibisono2@gmail.com" },
    { name: "Roy Romadhon", email: "roy.rmd.studio@gmail.com" },
    { name: "Lukas Henggrawan", email: "henggrawan.lukas@gmail.com" },
    { name: "Soerbakti_reza12", email: "soerbakti.reza12@gmail.com" },
    { name: "Yulius Hendrawan", email: "gameefbi@gmail.com" },
    { name: "Yanto", email: "yantolewen99@gmail.com" },
    { name: "Matthew", email: "matthewsebastian83@yahoo.com" },
    { name: "sbkoko_project", email: "sbkoko.project@gmail.com" },
    { name: "Raditya", email: "nradityoa23@gmail.com" },
    { name: "Musmualim Chaniago", email: "musmualimchaniago@gmail.com" },
    { name: "Anatolyreza", email: "Anatolyreza@gmail.com" },
    { name: "Pradityo Richi A", email: "arsitektur09@gmail.com" },
    { name: "Agam Gumelar", email: "agamgumelar13@gmail.com" },
    { name: "Abdurrahman Shiddiq", email: "abdurrahmanshiddiq30@gmail.com" },
    { name: "Sufyan", email: "sufyan.mishbahuddin@gmail.com" },
    { name: "Andirian", email: "andirian05@gmail.com" },
    { name: "Ade Maulana", email: "ademaulanairvansyah3@gmail.com" },
    { name: "Ricky", email: "ricky.cilegon@gmail.com" },
    { name: "Ritchi Reme", email: "ritchiereme25@gmail.com" },
    { name: "Bionprojects_id", email: "bionprojects.id@gmail.com" },
    { name: "Simon Adiputra", email: "simonadiputra51@gmail.com" },
    { name: "Andinata Chandra", email: "silentlykidd4@gmail.com" },
    { name: "Azmi Fata Akalili", email: "azmifata.ak@gmail.com" },
    { name: "Nauval Balad", email: "nauvalbalad@gmail.com" },
    { name: "Andi", email: "andi.azsahrah228@gmail.com" },
    { name: "Jesslyn", email: "jesslyn.jesslyn@yahoo.com" },
    { name: "Arya", email: "aryadwiprasetya102001@gmail.com" },
    { name: "Arkendrastudio", email: "arkendrastudio@gmail.com" },
    { name: "Reza Saputra", email: "risqireza01@gmail.com" },
    { name: "Octya Pratama", email: "octya.pratama2001@gmail.com" },
    { name: "Ajnyana", email: "ajnyana@gmail.com" },
    { name: "Ka", email: "24512131@students.uii.ac.id" },
    { name: "Krisna", email: "krisnantara97@gmail.com" },
    { name: "Arcndoves", email: "arcndoves@gmail.com" },
    { name: "Akbar", email: "akbar.nugraha24@gmail.com" },
    { name: "Miqbalazh", email: "miqbalazh@gmail.com" },
    { name: "Eka Yudha", email: "xayudha@gmail.com" },
    { name: "Gihonlda", email: "gihonlda@gmail.com" },
    { name: "Irham", email: "irhamiraihan@gmail.com" },
    { name: "Bagus", email: "bagusardhaputra5@gmail.com" },
    { name: "Dyah", email: "dyah.istiana2@gmail.com" },
    { name: "Irkhamulloh", email: "if3dstudio.id@gmail.com" },
    { name: "Abdul Hadi", email: "abdulhadi290898@gmail.com" },
    { name: "Komang", email: "komangk26@gmail.com" },
    { name: "Imadudin Mahmud", email: "imaddudin13@gmail.com" },
    { name: "Yoga Novian Karuniadi", email: "d1031201004@student.untan.ac.id" },
    { name: "Rijalisnanda", email: "rijalisnanda@gmail.com" },
    { name: "Tokoomsugi", email: "tokoomsugi@gmail.com" },
    { name: "Anthonychan", email: "accenthusemail@gmail.com" },
    { name: "Alfiananda Rahmadiska", email: "alfiananda17@gmail.com" },
    { name: "Hariananda Aulivio", email: "hariananda.aulivio@gmail.com" },
    { name: "Matthew Eduardus", email: "udevisual@gmail.com" },
    { name: "Arizal Tri Wahyuda", email: "arizaltriwahyuda@gmail.com" },
    { name: "Jewelalverna", email: "jewelalverna@gmail.com" },
    { name: "Apri", email: "aprie.praka@gmail.com" },
    { name: "Adiidrft", email: "adiidrft@gmail.com" },
    { name: "jesslyn", email: "serialcollab71@gmail.com" },
    { name: "Komang", email: "komangjayu@gmail.com" },
    { name: "Rendy Recoba", email: "seniarsitek@gmail.com" },
    { name: "Demy Erdieyandi", email: "demy.project2@gmail.com" },
    { name: "Mh Basri", email: "basri1803@gmail.com" },
    { name: "Nicky Hartanto Winata", email: "nickyhartx@gmail.com" },
    { name: "Zulfahmi afifi", email: "zulfahmi.afifi@gmail.com" },
    { name: "Hilmi Khairullah", email: "hilmikhairulla@gmail.com" },
    { name: "Norita", email: "nliuvander@gmail.com" },
    { name: "Jimmy", email: "jimmy_on_go@yahoo.co.id" },
    { name: "Radix N", email: "radixnormandy@gmail.com" },
    { name: "M shahab", email: "shahab.study@gmail.com" },
    { name: "Ninik Kurniawati", email: "niniknon@gmail.com" },
    { name: "Bagus Saputra", email: "gabzettoi@gmail.com" },
    { name: "Irfan Hardiansyah", email: "irfanhardiansyah@vershome.com" },
    { name: "Wayan Adi Nugraha", email: "wayanadinugraha090@gmail.com" },
    { name: "zulfahmi afifi", email: "zulfahmi.afifi@gmail.com" },
    { name: "Alfi Dinata", email: "alfidinatabsc@gmail.com" },
    { name: "Farchan Zain", email: "datoksenga@gmail.com" },
    { name: "ALAIKA SALAMUDDIN", email: "alaikasalamuddin7@gmail.com" },
    { name: "Nur Sutoyo", email: "ns.toyodipo@gmail.com" },
    { name: "Rizaly Nur", email: "solidtritama@yahoo.com" },
    { name: "Gus Ade Wistika", email: "gusadewistika210401@gmail.com" },
    { name: "Ari sandi", email: "ari801759@gmail.com" },
    { name: "Muh Fadhlan", email: "fadhlan2302@gmail.com" },
    { name: "Ahmad Safriyanto", email: "ahmadsyarieftatang16@gmail.com" },
    { name: "AGUNG FERIANTO", email: "agung_ferianto@yahoo.co.id" },
    { name: "Solichul Arif", email: "arif170372a@gmail.com" },
    { name: "Muhammad Hasan Habibi", email: "dunilus7@gmail.com" },
    { name: "Lukas Henggrawan", email: "henggrawan.lukas@gmail.com" },
    { name: "Arizal Tri Wahyuda", email: "arizaltriwahyuda@gmail.com" },
    { name: "Dandy Ananda", email: "dandy.kanawasena@gmail.com" },
    { name: "Gunawan Akbar Sakti", email: "vincent.goen@gmail.com" },
    { name: "muhammad Junaidi", email: "muhammadjunaidi110897@gmail.com" },
    { name: "Abdul Hadi", email: "abdulhadi290898@gmail.com" },
    { name: "Disky Saputra Wardani", email: "diskys10@gmail.com" },
    { name: "taufiq rokhman", email: "studiosalaksa@gmail.com" },
    { name: "Kurnia Ageng Firmanda", email: "kurnia.afirmand25@gmail.com" },
    { name: "Fulki F L", email: "datapersonal.ffl@gmail.com" },
    { name: "Chalim A", email: "chalim.star@gmail.com" },
    { name: "Gabriel Batistuta", email: "gabriel.6batistuta@gmail.com" },
    { name: "Nusada Putra", email: "goeznusadacvl@gmail.com" },
    { name: "Mochamad Nawir", email: "moch.nawir@gmail.com" },
    { name: "Renza Chen", email: "rassociatesbureau@gmail.com" },
    { name: "Roy Romadhon", email: "roy.rmd.studio@gmail.com" },
    { name: "Endra Wibisono", email: "endrawibisono2@gmail.com" },
    { name: "Novia Fatmawati", email: "noviafaa7@gmail.com" },
    { name: "Agam Gumelar", email: "agamgumelar13@gmail.com" },
    { name: "ramdhan omar", email: "gajah.bengkaks@gmail.com" },
    { name: "Sany H", email: "sanyhusnainyyy94@gmail.com" },
    { name: "KOMANG KRISNA", email: "krisnaputra4679@gmail.com" },
    { name: "Yn Y", email: "ypratamadesain@gmail.com" },
    { name: "Joko widodo", email: "jokowi84@gmail.com" },
    { name: "Up Design", email: "taufikarsitek777@gmail.com" },
    { name: "Lingga Wiraaditama", email: "lingga_wiraaditama@yahoo.com" },
    { name: "Albert utama", email: "albert.utama755@gmail.com" },
    { name: "Amalia Alifiani", email: "simbgamalia23@gmail.com" },
    { name: "Andika Arifiansyah", email: "andikaarifiansyah@gmail.com" },
    { name: "matthew ricky", email: "matthew_rickys@yahoo.com" },
    { name: "Alfiananda Rahmadiska", email: "alfiananda17@gmail.com" },
    { name: "Putra Suastawan", email: "putrasuastawan@gmail.com" },
    { name: "Imam Saputra", email: "arch.mamsa90@gmail.com" },
    { name: "Apri", email: "aprie.praka@gmail.com" },
    { name: "Choirun Niam", email: "niampadsix@gmail.com" },
    { name: "Gde Dita", email: "gedeakunnintendo@gmail.com" },
    { name: "Hilmi Khairullah", email: "hkhairullah2000@gmail.com" },
    { name: "Dhimas Sulthan", email: "savoircollectiva@gmail.com" },
    { name: "Wahyudi Gusrifanjaya", email: "Wgusrifanjaya@gmail.com" },
    { name: "Acto arga", email: "thinkingofchrist@gmail.com" },
    { name: "Edy Hariyanto", email: "arya2nd@gmail.com" },
    { name: "Desmon Mongdong", email: "chanvalentine02@gmail.com" },
    { name: "Andhy Bowie", email: "andhybowie@gmail.com" },
    { name: "Ahmad Arfandi", email: "epenbrutal@gmail.com" },
    { name: "Aditya Bambang", email: "adityabt2006@gmail.com" },
    { name: "Hermana Ega", email: "hermanaega0107@gmail.com" },
    { name: "Farid", email: "faridsuka@gmail.com" },
    { name: "ISWANTONO WIDARTO", email: "ken.widarto@gmail.com" },
    { name: "Komang Adi", email: "adiidrft@gmail.com" },
    { name: "Aris ade", email: "adesaputra5858@gmail.com" },
    { name: "Nurul", email: "nurul.panjaya@gmail.com" },
    { name: "Prima Adi Y", email: "prima.adi.yudha@gmail.com" },
    { name: "Imam Aldi", email: "yourfutureimam96@gmail.com" },
    { name: "Imam Budi Prasetyo", email: "imam.sleman123@gmail.com" },
    { name: "Agung gilbran", email: "agunggilbran3@gmail.com" },
    { name: "Usamah Al Ghifari", email: "osa.ghifari@gmail.com" },
    { name: "hafizh ramadhan", email: "hafizhramadhann22@gmail.com" },
    { name: "nliuvander", email: "nliuvander@gmail.com" },
    { name: "hirfal herdinal", email: "hirfalherdinal211@gmail.com" },
    { name: "Bima Wirama", email: "bimawirama@gmail.com" },
    { name: "Ryan Fahri Husaini", email: "ryanfahrihusaini@gmail.com" },
    { name: "Yanto Lewen", email: "yantolewen99@gmail.com" },
    { name: "krisna choirudin", email: "krisnachoirudin1@gmail.com" },
    { name: "DameLusyana", email: "damelusyana1@gmail.com" },
    { name: "Gede Dhiyo Pranadhika Tanaya", email: "dhiyopranadhikacundamani@gmail.com" },
    { name: "Jimmy", email: "jimmy_on_go@yahoo.co.id" },
    { name: "Nur rohman", email: "armaindesign@gmail.com" },
    { name: "Nur Rifai", email: "nur.rifazul@gmail.com" },
    { name: "Digit Dewayanda", email: "digitdewayanda@gmail.com" },
    { name: "Daniel Purnomo", email: "danielpurnomo2024@gmail.com" },
    { name: "Rysyad Firmansyah", email: "firmansyahrysyad@gmail.com" },
    { name: "Tri Laksono", email: "tri.online2010@gmail.com" },
    { name: "Anggun Regla", email: "boncibon13@gmail.com" },
    { name: "Mohammad Zaenal Arifin", email: "asthanawa@gmail.com" },
    { name: "cakra caesar", email: "cakracaesarwardhana@gmail.com" },
    { name: "Rheza Reinaldo", email: "azehrodlanier@gmail.com" },
    { name: "Abdullah Fikri", email: "fikrishahab22@gmail.com" },
    { name: "Fransiskus Xaverius Purnomo", email: "fx.purnomo@gmail.com" },
    { name: "Aryan Dhani", email: "mr.aryandhani@gmail.com" },
    { name: "Agung Pribadi", email: "dahilullah@gmail.com" },
    { name: "Andre Maulana", email: "andremln27@gmail.com" },
    { name: "Andreas Mukin", email: "andimukin@gmail.com" },
    { name: "Hanes Budi", email: "hanesbudistudio@gmail.com" },
    { name: "Rendy Recoba", email: "seniarsitek@gmail.com" },
    { name: "Aditya Tri", email: "madaonfire@gmail.com" },
    { name: "Muhammad Waldy", email: "waldysiddiq@gmail.com" },
    { name: "M. Irsan Latief", email: "mohd.irsan28@gmail.com" },
    { name: "Muhammad Amin Rosyadi", email: "moehammedamien16sanje@gmail.com" },
    { name: "Andreas Kadang", email: "andreaskadang@gmail.com" },
    { name: "Ghazian Bahaduri", email: "ghazianaf21@gmail.com" },
    { name: "Khoirul Rijal", email: "khoirulrijal4625@gmail.com" },
    { name: "Putu Jiesta Wulandari", email: "jiestawulandarii@gmail.com" },
    { name: "Geronimo Shah", email: "geronimo.shah@gmail.com" },
    { name: "Angga Aldiansyah", email: "anggaaldsyh99@gmail.com" },
    { name: "Esa Mahaputra", email: "esamahaputra16@gmail.com" },
    { name: "Rafif Brilianto", email: "rafifbrilianto@gmail.com" },
    { name: "Ala Hidayah", email: "alaahsm27@gmail.com" },
    { name: "Ricky Farras Khoirullah", email: "farrasricky18@gmail.com" },
    { name: "Demy Erdieyandi", email: "d.erdieyandi@gmail.com" },
    { name: "Asep Roni", email: "asepalam46@gmail.com" },
    { name: "Supriyatna", email: "supriyatna040807@gmail.com" },
    { name: "Ferry", email: "ferry.ars.28@gmail.com" },
    { name: "Dicky Darmawan", email: "dickydarmawann32@gmail.com" },
    { name: "Muhammad Daffa Putra agusti", email: "muhammaddaffaputraagusti@gmail.com" },
    { name: "Muhammad haykal", email: "haykaldjamil42@gmail.com" },
    { name: "Clifford Sutedjo", email: "cliffordsutedjo@yahoo.com" },
    { name: "Dody Kindarch", email: "dodykindarch@gmail.com" },
    { name: "zoland Bintang", email: "rzoland43@gmail.com" },
    { name: "Matthew Sebastian", email: "matthewsebastian83@yahoo.com" },
    { name: "Roynaldo Stevanus", email: "ciamiktok@gmail.com" },
    { name: "Farras Arkan", email: "farras.krein@gmail.com" },
    { name: "Muchammad Jordan Firzatullah", email: "jordanfirzatullah@gmail.com" },
    { name: "Aris Munawar", email: "arismunawwar@gmail.com" },
    { name: "Ahmad Fauzan", email: "hammuzjak@gmail.com" },
    { name: "Lutfhi Fauzan Astsani", email: "lutfhi.fa@gmail.com" },
    { name: "wawan Kyt", email: "onekyt88@gmail.com" },
    { name: "Mohamad Hendra Basri", email: "basri1803@gmail.com" },
    { name: "Agus Suandi", email: "a.g.desain@gmail.com" },
    { name: "Ade Dondan", email: "adegresdondan@gmail.com" },
    { name: "Muhammad Najid Azma", email: "mhmdnajid31@gmail.com" },
    { name: "Herlina Karlai", email: "herlina.karlai@gmail.com" },
    { name: "joko prakosa", email: "jokoarchgg@gmail.com" },
    { name: "CHANDRA MARTHA DINATA", email: "chandrakreasiproperti@gmail.com" },
    { name: "Bambang Sulis", email: "bambangsulissetyawan01@gmail.com" },
    { name: "Muhammad Dhiaul haq", email: "muhammadulhaq.mu@gmail.com" },
    { name: "Sie Arifin Ciputra", email: "viewsienstudio@gmail.com" },
    { name: "Malik ilhamudin", email: "malikilham28@gmail.com" },
    { name: "Hendri Hermawan", email: "hendrihermawan710@gmail.com" },
    { name: "Lily Gun", email: "guntoro.lily@gmail.com" },
    { name: "ngurah wiraa", email: "ngurahharley677@gmail.com" },
    { name: "Muhammad Zulfikar Aslon", email: "zulfikaraslon@gmail.com" },
    { name: "Alvin Maskur", email: "alhamdaalvin@gmail.com" },
    { name: "Ritchi Reme", email: "ritchiereme25@gmail.com" },
    { name: "Yudin Liputo", email: "YudinLiputo@gmail.com" },
    { name: "Adenan Syakur", email: "adenan.reg@gmail.com" },
    { name: "HarrisTanoyo", email: "harristanoyo92@gmail.com" },
    { name: "alle al", email: "aliefalmukarrom21@gmail.com" },
    { name: "Andrew Karta", email: "andrew.karta89@gmail.com" },
    { name: "Adhi Krisna", email: "adhikrisna.ak@gmail.com" },
    { name: "Viktor Geolo", email: "viktorgulo19@gmail.com" },
    { name: "Shan MT", email: "syantrimt@gmail.com" },
    { name: "Mutamam jayadi", email: "drafteracademy67@gmail.com" },
    { name: "I Nyoman", email: "fernandaagus666@gmail.com" },
    { name: "Anton Sobirin", email: "77ansharin@gmail.com" },
    { name: "Yohanes Kristian", email: "yo.gun0709@gmail.com" },
    { name: "Stanley", email: "eon.architects18@gmail.com" },
    { name: "Ansharin Tujuh", email: "desainaksen77@gmail.com" },
    { name: "jaril safii", email: "jaril.saf@gmail.com" },
    { name: "Fakhri Aulia", email: "fakhri.aulia.ars@gmail.com" },
    { name: "Raihan", email: "devstraicher@gmail.com" },
    { name: "Yandy Arianto", email: "sobatkomuniti@gmail.com" },
    { name: "Agung Hidayat", email: "okynotatsukero@gmail.com" },
    { name: "Dendi Satria", email: "dendisatria33@gmail.com" },
]

async function main() {
    const hashedPassword = await bcrypt.hash('password', 10)
    const now = new Date()

    console.log(`Starting migration for ${users.length} users...`)

    for (const user of users) {
        try {
            const result = await prisma.user.upsert({
                where: { email: user.email },
                update: {
                    name: user.name,
                    emailVerified: now,
                },
                create: {
                    email: user.email,
                    name: user.name,
                    password: hashedPassword,
                    emailVerified: now,
                },
            })
            console.log(`Upserted: ${result.email}`)
        } catch (error) {
            console.error(`Error upserting ${user.email}:`, error)
        }
    }

    console.log('Migration completed.')
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
